version: '3'
services:
  portal-housagotchi-db:
    image: postgres
    volumes:
      - /app/portal/housagotchi/db/config:/etc/postgresql
      - /app/portal/housagotchi/logs:/var/log/postgresql
      - /app/portal/housagotchi/db/databases:/var/lib/postgresql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: portal-housagotchi
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: portal-housagotchi
